---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-app-prod-env
  namespace: prod-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: group-app-prod-env
  template:
    metadata:
      labels:
        app: group-app-prod-env
        env: prod-env
    spec:
      serviceAccountName: group-app-service-account
      containers:
      - name: group-app-prod-env
        image: dampado/springreetings:latest
        ports:
        - containerPort: 8080
        