---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-app
  namespace: test-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: group-app
      env: test-env
  template:
    metadata:
      labels:
        app: group-app
        env: test-env
    spec:
      serviceAccountName: group-app-service-account
      containers:
      - name: group-app-test-env
        image: dampado/springreetings:latest  # Update it to yours (just the username mostly)
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi