---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-app-test-env
  namespace: test-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: group-app-test-env
  template:
    metadata:
      labels:
        app: group-app-test-env
        env: test-env
    spec:
      serviceAccountName: group-app-service-account
      containers:
      - name: group-app-test-env
        image: dampado/springreetings:latest  # Update it to yours (just the username mostly)
        ports:
        - containerPort: 8080
        
        